## Install Packages

In [50]:
%pip install seaborn
%matplotlib inline

Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.9/site-packages (0.11.2)
Requirement already satisfied: pandas>=0.23 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.3.4)
Requirement already satisfied: matplotlib>=2.2 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (3.4.3)
Requirement already satisfied: numpy>=1.15 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.20.3)
Requirement already satisfied: scipy>=1.0 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.7.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (3.0.4)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->seaborn) (2021.3)
Note: you may need to restart the kernel to use updated packages.

In [51]:
pip install plotly

Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.9/site-packages (5.7.0)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from plotly) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from plotly) (8.0.1)
Note: you may need to restart the kernel to use updated packages.

In [52]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from time import time
from sklearn.model_selection import ShuffleSplit, GridSearchCV
from scipy.stats import randint
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report

## Import CSV FILES

In [53]:
df_train = pd.read_csv("/Users/isa/Desktop/LeafClassification/train.csv")
df_test = pd.read_csv("/Users/isa/Desktop/LeafClassification/test.csv")

In [54]:
df_train.head()
df = df_train.copy()

In [79]:
df_test.head()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,0.023438,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,0.023438,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,0.005859,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,0.001953,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,0.000000,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [56]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit


encoder=LabelEncoder()
le=encoder.fit(df_train.species)
labels=le.transform(df_train.species)
classes=list(le.classes_)

In [57]:
df_train=df_train.drop(['id','species'],axis=1)
test_id=df_test.id
df_test=df_test.drop(['id'],axis=1)

In [58]:
df_test

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.000000,0.005859,0.023438,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.000000,0.033203,0.023438,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.000000,0.011719,0.005859,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.000000,0.003906,0.001953,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.000000,0.005859,0.000000,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,0.000000,0.000000,0.003906,0.015625,0.041016,0.000000,0.017578,0.000000,0.005859,0.013672,...,0.098633,0.000000,0.004883,0.000000,0.003906,0.0,0.0,0.018555,0.000000,0.000977
590,0.000000,0.003906,0.003906,0.005859,0.017578,0.000000,0.017578,0.005859,0.000000,0.005859,...,0.012695,0.004883,0.004883,0.002930,0.009766,0.0,0.0,0.090820,0.000000,0.016602
591,0.017578,0.029297,0.015625,0.013672,0.003906,0.015625,0.025391,0.000000,0.000000,0.009766,...,0.073242,0.000000,0.028320,0.000000,0.001953,0.0,0.0,0.000000,0.042969,0.006836
592,0.013672,0.009766,0.060547,0.025391,0.035156,0.025391,0.039062,0.000000,0.003906,0.023438,...,0.003906,0.000000,0.000977,0.000000,0.011719,0.0,0.0,0.000000,0.011719,0.018555
593,0.000000,0.117190,0.000000,0.019531,0.000000,0.136720,0.001953,0.005859,0.000000,0.007812,...,0.107420,0.012695,0.016602,0.000977,0.004883,0.0,0.0,0.015625,0.000000,0.017578

In [59]:
uniquelables=np.unique(labels)

## Train and Test Split

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(df_train,labels,test_size=0.3,shuffle=True,stratify=labels)

In [61]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

pipe_lr=Pipeline([('scl', StandardScaler()), ('pca', PCA(n_components=10)), ('clf', LogisticRegression(random_state=1))])
pipe_lr.fit(X_train, y_train)
print(pipe_lr.score(X_test, y_test))

0.9494949494949495

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## K Fold Cross Validation

In [62]:
from sklearn.model_selection import cross_val_score,KFold
X=df_train
Y=df['species']
logreg=LogisticRegression()
kf=KFold(n_splits=10)
score=cross_val_score(logreg,X,Y,cv=kf)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores are [0.21212121 0.22222222 0.13131313 0.13131313 0.18181818 0.17171717
 0.25252525 0.21212121 0.12121212 0.18181818]
Average Cross Validation score :0.18181818181818182

### Most suitable parameter

In [63]:
cv_sets = ShuffleSplit(n_splits=10,test_size=0.30,random_state=42)
classifiers = [SVC(), KNeighborsClassifier()]
params = [{'kernel':('linear','poly','sigmoid','rbf'),'C':[0.01,0.05,0.025,0.07,0.09,1.0], 'gamma':['scale'], 'probability':[True]},
          {'n_neighbors': [3,5,7,9]}]

In [64]:
best_estimators = []
for classifier, param in zip(classifiers, params):
    grid = GridSearchCV(classifier,param,cv=cv_sets)
    grid = grid.fit(X_train,y_train)
    best_estimators.append(grid.best_estimator_)

In [65]:
best_estimators

[SVC(kernel='poly', probability=True), KNeighborsClassifier(n_neighbors=3)]

In [66]:
param_dist = {"max_depth": [3, None],
              "max_features": randint(1, 9),
              "min_samples_leaf": randint(1, 9),
              "criterion": ["gini", "entropy"]}
tree = DecisionTreeClassifier()

tree_cv = RandomizedSearchCV(tree, param_dist, cv=5)

tree_cv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, None],
                                        'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7feb3985be20>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7feb398572b0>})

In [67]:
tree_cv.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_features=8, min_samples_leaf=3)

## MLOPS

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
model_1 = make_pipeline(StandardScaler(), LogisticRegression())

print(model_1.fit(X_train,y_train))

print(model_1.score(X_test,y_test))


y_pred = model_1.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])
0.98989898989899
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 3]]

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [69]:
model_2 = make_pipeline(StandardScaler(), SVC())

print(model_2.fit(X_train,y_train))

print(f'score Model:',model_2.score(X_test,y_test))

y_pred = model_2.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])
score Model: 0.98989898989899
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 3]]

In [70]:
model_3 = make_pipeline(StandardScaler(), KNeighborsClassifier())

print(model_3.fit(X_train,y_train))

print(f'score Model:',model_3.score(X_test,y_test))

y_pred = model_3.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier())])
score Model: 0.9663299663299664
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 3]]

In [71]:
model_4 = make_pipeline(StandardScaler(),DecisionTreeClassifier())

print(model_4.fit(X_train,y_train))

print(f'score Model:',model_4.score(X_test,y_test))

y_pred = model_4.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier', DecisionTreeClassifier())])
score Model: 0.6464646464646465
[[2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 1]]

In [72]:
model_5 = make_pipeline(StandardScaler(),GaussianNB())

print(model_5.fit(X_train,y_train))

print(f'score Model:',model_5.score(X_test,y_test))

y_pred = model_5.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gaussiannb', GaussianNB())])
score Model: 0.5420875420875421
[[2 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 3]]

In [73]:
values= [LogisticRegression(), SVC(), KNeighborsClassifier(), DecisionTreeClassifier(), GaussianNB()]

keys= ['LogisticRegression',
      'SVC', 
       'KNeighborsClassifier', 
       'DecisionTreeClassifier', 
       'GaussianNB']

models= dict(zip(keys,values))
accuracy_scores=[]
train_times=[]

for key,value in models.items():
  t = time()
  value.fit(X_train,y_train)
  duration = (time() - t) / 60
  y_pred= value.predict(X_test)
  accuracy= accuracy_score(y_test, y_pred)
  accuracy_scores.append(accuracy)
  train_times.append(duration)   
  print(key)
  print(round(accuracy * 100, 2))
  #cm = confusion_matrix(y_test, y_pred)
  #print(cm)
  #print(classification_report(y_test, y_pred))

LogisticRegression
60.27
SVC
88.55
KNeighborsClassifier
82.83
DecisionTreeClassifier
63.97
GaussianNB
54.21

In [74]:
test_pred = model_5.predict(df_test)
test_pred

array([56, 55,  1, 19, 14,  3, 41, 28,  0, 19, 43, 12, 75, 10, 52, 56, 69,
       41, 13, 71, 96, 69, 57, 93, 11, 47, 69, 15, 35, 70, 53, 16, 47, 50,
        4, 73, 14, 14, 36, 93, 19, 19, 19,  9, 71, 36, 96, 96, 41, 55, 86,
       19, 55, 94, 93, 73, 62, 54, 87, 98, 88, 26, 87, 59, 12, 11, 48, 74,
       13,  4, 85, 57, 29,  7, 46, 12, 73, 41, 36, 10, 55, 73, 87, 24, 87,
        2, 23, 83, 69, 36, 41, 69, 70, 46, 70, 56, 41, 14,  7, 47, 12, 93,
        3, 12, 69, 69, 12, 96, 64, 19, 93, 93, 19, 36, 16, 26, 60, 87,  6,
       44, 34, 90, 60, 14, 75, 83, 56, 92, 39, 23, 46,  2, 41, 96, 24, 93,
       69, 28, 69, 81, 69, 51, 69, 52, 60, 52, 14, 55, 81, 47, 41, 20, 59,
       35, 86,  1, 26, 96, 96, 83, 87, 60, 93, 79, 19, 79, 93, 47, 65, 97,
       87, 21, 79, 87, 11, 10, 58, 94, 97, 73, 36, 45, 73, 55, 47, 80, 87,
       94, 40, 49, 73, 70, 36, 93, 81, 95, 74, 91, 29, 56, 80, 93, 78, 45,
       69,  9, 78, 85, 44, 73, 92, 47,  2, 59, 41, 96, 36, 32, 79, 78, 91,
       69, 44, 96,  5, 79, 49, 69, 94, 36, 92, 88, 90, 79, 36, 38, 48, 12,
       76, 27, 70, 71, 44, 70, 33, 96, 69, 82, 34, 69, 19, 69, 48, 20, 66,
       64, 47, 56, 12, 73,  9,  3, 56, 26, 69, 71, 47, 47, 58, 19, 12, 78,
       73, 11, 83, 65, 67, 38,  0, 54,  3, 69, 19, 97, 80, 44, 73, 69, 54,
       12, 26, 51, 33, 93, 41, 11, 97, 11, 83,  2, 43, 83, 42, 86,  2, 73,
       96, 83, 26, 20, 63, 50, 16, 34, 87, 95, 98, 78, 83, 60, 80, 58, 87,
       14, 91, 96, 93, 50, 56, 93, 19, 46, 41, 93,  0, 33, 73, 36, 62, 48,
       69,  6, 26, 91, 73, 81, 12, 85, 47,  6, 79,  2, 36, 35, 73,  6, 80,
       80, 82, 56, 96, 69, 43, 33, 73, 19, 71, 47, 59, 69, 66, 86, 98, 50,
       90, 64, 59, 11, 79, 56, 87, 49, 48, 85, 16, 15, 69, 14, 89, 44,  7,
       78, 13, 55, 69, 83, 44, 19, 69, 47,  9, 36, 69, 96, 50, 82, 69, 79,
       22, 92, 72, 47, 19, 11, 87, 56, 80, 39,  0, 65, 66, 47,  8, 92, 80,
        4, 26,  3, 73, 87, 36, 96, 39, 56, 73, 85, 78,  7, 22, 69,  8, 95,
       85, 62, 10, 12,  0,  2, 47, 86, 12, 52,  3, 49, 47, 87, 52, 41, 47,
       88, 82, 45, 40, 77, 19, 75, 74,  7, 64, 54, 78, 63, 83, 21, 96, 88,
       83, 93, 47, 12, 16, 36, 85, 12, 77, 57, 56, 82, 70, 58, 69, 17, 36,
       77, 44, 66, 83, 35, 55,  0, 96, 91, 20, 19, 15, 10, 69, 71, 73, 47,
       39, 85, 16, 19, 45, 87,  6, 73, 69, 69, 80, 47, 85, 69, 85, 47, 36,
       77, 58, 69, 12, 91, 63, 97, 76, 69, 87, 47, 14,  0, 36, 41, 14, 12,
        0, 86, 46, 19, 11, 47, 69, 19, 58, 13, 93, 41, 54, 11, 72, 56, 32,
       73, 36,  3, 47, 92, 16, 81, 37, 14, 93, 80, 12, 46, 25, 55,  7, 37,
       93,  0, 20, 41, 10, 91, 69, 81, 53, 18, 27, 11, 12, 54, 73, 36])

In [75]:
sample_df=pd.read_csv('/Users/isa/Desktop/LeafClassification/sample_submission.csv',index_col=False)
print(sample_df)

       id  Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  \
0       4         0.010101         0.010101   0.010101     0.010101
1       7         0.010101         0.010101   0.010101     0.010101
2       9         0.010101         0.010101   0.010101     0.010101
3      12         0.010101         0.010101   0.010101     0.010101
4      13         0.010101         0.010101   0.010101     0.010101
..    ...              ...              ...        ...          ...
589  1576         0.010101         0.010101   0.010101     0.010101
590  1577         0.010101         0.010101   0.010101     0.010101
591  1579         0.010101         0.010101   0.010101     0.010101
592  1580         0.010101         0.010101   0.010101     0.010101
593  1583         0.010101         0.010101   0.010101     0.010101

     Acer_Palmatum  Acer_Pictum  Acer_Platanoids  Acer_Rubrum  Acer_Rufinerve  \
0         0.010101     0.010101         0.010101     0.010101        0.010101
1         0.010101     0.010101         0.010101     0.010101        0.010101
2         0.010101     0.010101         0.010101     0.010101        0.010101
3         0.010101     0.010101         0.010101     0.010101        0.010101
4         0.010101     0.010101         0.010101     0.010101        0.010101
..             ...          ...              ...          ...             ...
589       0.010101     0.010101         0.010101     0.010101        0.010101
590       0.010101     0.010101         0.010101     0.010101        0.010101
591       0.010101     0.010101         0.010101     0.010101        0.010101
592       0.010101     0.010101         0.010101     0.010101        0.010101
593       0.010101     0.010101         0.010101     0.010101        0.010101

     ...  Salix_Fragilis  Salix_Intergra  Sorbus_Aria  Tilia_Oliveri  \
0    ...        0.010101        0.010101     0.010101       0.010101
1    ...        0.010101        0.010101     0.010101       0.010101
2    ...        0.010101        0.010101     0.010101       0.010101
3    ...        0.010101        0.010101     0.010101       0.010101
4    ...        0.010101        0.010101     0.010101       0.010101
..   ...             ...             ...          ...            ...
589  ...        0.010101        0.010101     0.010101       0.010101
590  ...        0.010101        0.010101     0.010101       0.010101
591  ...        0.010101        0.010101     0.010101       0.010101
592  ...        0.010101        0.010101     0.010101       0.010101
593  ...        0.010101        0.010101     0.010101       0.010101

     Tilia_Platyphyllos  Tilia_Tomentosa  Ulmus_Bergmanniana  Viburnum_Tinus  \
0              0.010101         0.010101            0.010101        0.010101
1              0.010101         0.010101            0.010101        0.010101
2              0.010101         0.010101            0.010101        0.010101
3              0.010101         0.010101            0.010101        0.010101
4              0.010101         0.010101            0.010101        0.010101
..                  ...              ...                 ...             ...
589            0.010101         0.010101            0.010101        0.010101
590            0.010101         0.010101            0.010101        0.010101
591            0.010101         0.010101            0.010101        0.010101
592            0.010101         0.010101            0.010101        0.010101
593            0.010101         0.010101            0.010101        0.010101

     Viburnum_x_Rhytidophylloides  Zelkova_Serrata
0                        0.010101         0.010101
1                        0.010101         0.010101
2                        0.010101         0.010101
3                        0.010101         0.010101
4                        0.010101         0.010101
..                            ...              ...
589                      0.010101         0.010101
590                      0.010101         0.010101
591                      0.010101         0.010101
592                      0.010101         0.010101
593                      0.010101         0.010101

[594 rows x 100 columns]

In [76]:
output = pd.DataFrame({'Id': test_id,
                       
                       'Labels': test_pred})
output.to_csv('submission.csv', index=False)
output.head()

   Id  Labels
0   4      56
1   7      55
2   9       1
3  12      19
4  13      14

In [77]:
final=pd.concat([output,sample_df],axis=1)
final.head()

,Id,Labels,id,Acer_Capillipes,Acer_Circinatum,Acer_Mono,Acer_Opalus,Acer_Palmatum,Acer_Pictum,Acer_Platanoids,...,Salix_Fragilis,Salix_Intergra,Sorbus_Aria,Tilia_Oliveri,Tilia_Platyphyllos,Tilia_Tomentosa,Ulmus_Bergmanniana,Viburnum_Tinus,Viburnum_x_Rhytidophylloides,Zelkova_Serrata
0,4,56,4,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
1,7,55,7,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
2,9,1,9,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
3,12,19,12,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
4,13,14,13,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101