## Install Packages

In [1]:
%pip install seaborn
%matplotlib inline

Requirement already satisfied: seaborn in /opt/anaconda3/lib/python3.9/site-packages (0.11.2)
Requirement already satisfied: matplotlib>=2.2 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (3.4.3)
Requirement already satisfied: pandas>=0.23 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.4.2)
Requirement already satisfied: numpy>=1.15 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.22.3)
Requirement already satisfied: scipy>=1.0 in /opt/anaconda3/lib/python3.9/site-packages (from seaborn) (1.7.3)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (3.0.4)
Requirement already satisfied: pillow>=6.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (9.0.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.9/site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.23->seaborn) (2021.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install plotly

Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.9/site-packages (5.7.0)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.9/site-packages (from plotly) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.9/site-packages (from plotly) (8.0.1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from time import time
from sklearn.model_selection import ShuffleSplit, GridSearchCV
from scipy.stats import randint
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report

## Import CSV FILES

In [4]:
df_train = pd.read_csv("/Users/isa/Desktop/LeafClassification/train.csv")
df_test = pd.read_csv("/Users/isa/Desktop/LeafClassification/test.csv")

In [5]:
df_train.head()
df = df_train.copy()

In [6]:
df_test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit


encoder=LabelEncoder()
le=encoder.fit(df_train.species)
labels=le.transform(df_train.species)
classes=list(le.classes_)

In [8]:
df_train=df_train.drop(['id','species'],axis=1)
test_id=df_test.id
df_test=df_test.drop(['id'],axis=1)

In [9]:
df_test

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.000000,0.005859,0.023438,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.000000,0.033203,0.023438,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.000000,0.011719,0.005859,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.000000,0.003906,0.001953,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.000000,0.005859,0.000000,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,0.000000,0.000000,0.003906,0.015625,0.041016,0.000000,0.017578,0.000000,0.005859,0.013672,...,0.098633,0.000000,0.004883,0.000000,0.003906,0.0,0.0,0.018555,0.000000,0.000977
590,0.000000,0.003906,0.003906,0.005859,0.017578,0.000000,0.017578,0.005859,0.000000,0.005859,...,0.012695,0.004883,0.004883,0.002930,0.009766,0.0,0.0,0.090820,0.000000,0.016602
591,0.017578,0.029297,0.015625,0.013672,0.003906,0.015625,0.025391,0.000000,0.000000,0.009766,...,0.073242,0.000000,0.028320,0.000000,0.001953,0.0,0.0,0.000000,0.042969,0.006836
592,0.013672,0.009766,0.060547,0.025391,0.035156,0.025391,0.039062,0.000000,0.003906,0.023438,...,0.003906,0.000000,0.000977,0.000000,0.011719,0.0,0.0,0.000000,0.011719,0.018555
593,0.000000,0.117190,0.000000,0.019531,0.000000,0.136720,0.001953,0.005859,0.000000,0.007812,...,0.107420,0.012695,0.016602,0.000977,0.004883,0.0,0.0,0.015625,0.000000,0.017578

In [10]:
uniquelables=np.unique(labels)

## Train and Test Split

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(df_train,labels,test_size=0.3,shuffle=True,stratify=labels)

In [12]:
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

pipe_lr=Pipeline([('scl', StandardScaler()), 
                  ('pca', PCA(n_components=10)), 
                  ('clf', LogisticRegression(random_state=1))])
pipe_lr.fit(X_train, y_train)
print(pipe_lr.score(X_test, y_test))

0.9494949494949495

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

## K Fold Cross Validation

In [13]:
from sklearn.model_selection import cross_val_score,KFold
X=df_train
Y=df['species']
logreg=LogisticRegression()
kf=KFold(n_splits=10)
score=cross_val_score(logreg,X,Y,cv=kf)
print("Cross Validation Scores are {}".format(score))
print("Average Cross Validation score :{}".format(score.mean()))

Cross Validation Scores are [0.21212121 0.22222222 0.13131313 0.13131313 0.18181818 0.17171717
 0.25252525 0.21212121 0.12121212 0.18181818]
Average Cross Validation score :0.18181818181818182

### Most suitable parameter

In [14]:
cv_sets = ShuffleSplit(n_splits=10,test_size=0.30,random_state=42)
classifiers = [SVC(), KNeighborsClassifier()]
params = [{'kernel':('linear','poly','sigmoid','rbf'),'C':[0.01,0.05,0.025,0.07,0.09,1.0], 'gamma':['scale'], 'probability':[True]},
          {'n_neighbors': [3,5,7,9]}]

In [15]:
best_estimators = []
for classifier, param in zip(classifiers, params):
    grid = GridSearchCV(classifier,param,cv=cv_sets)
    grid = grid.fit(X_train,y_train)
    best_estimators.append(grid.best_estimator_)

In [16]:
best_estimators

[SVC(probability=True), KNeighborsClassifier(n_neighbors=3)]

In [17]:
param_dist = {"max_depth": [3, None],
              "max_features": randint(1, 9),
              "min_samples_leaf": randint(1, 9),
              "criterion": ["gini", "entropy"]}
tree = DecisionTreeClassifier()

tree_cv = RandomizedSearchCV(tree, param_dist, cv=5)

tree_cv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [3, None],
                                        'max_features': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fed694f9550>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7fed69532310>})

In [18]:
tree_cv.best_estimator_

DecisionTreeClassifier(max_features=7, min_samples_leaf=5)

## MLOPS

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
model_1 = make_pipeline(StandardScaler(), LogisticRegression())

print(model_1.fit(X_train,y_train))

print(model_1.score(X_test,y_test))


y_pred = model_1.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Recall: ",recall_score(y_test, y_pred, average='micro'))
print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])
0.9764309764309764
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 3]]
Recall:  0.9764309764309764
Precision: 0.9764309764309764
F1 PuanÄ±: 0.9764309764309764

/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [50]:
model_2 = make_pipeline(StandardScaler(), SVC())

print(model_2.fit(X_train,y_train))

print(f'score Model:',model_2.score(X_test,y_test))

y_pred = model_2.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Recall: ",recall_score(y_test, y_pred, average='micro'))
print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])
score Model: 0.9764309764309764
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 3]]
Recall:  0.9764309764309764
Precision: 0.9764309764309764
F1 PuanÄ±: 0.9764309764309764

In [46]:
model_3 = make_pipeline(StandardScaler(), KNeighborsClassifier())

print(model_3.fit(X_train,y_train))

print(f'score Model:',model_3.score(X_test,y_test))

y_pred = model_3.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Recall: ",recall_score(y_test, y_pred, average='micro'))
print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier())])
score Model: 0.9595959595959596
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 2]]
Recall:  0.9595959595959596
Precision: 0.9595959595959596
F1 PuanÄ±: 0.9595959595959596

In [45]:
model_4 = make_pipeline(StandardScaler(),DecisionTreeClassifier())

print(model_4.fit(X_train,y_train))

print(f'score Model:',model_4.score(X_test,y_test))

y_pred = model_4.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Recall: ",recall_score(y_test, y_pred, average='micro'))
print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier', DecisionTreeClassifier())])
score Model: 0.6599326599326599
[[3 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 2]]
Recall:  0.6599326599326599
Precision: 0.6599326599326599
F1 PuanÄ±: 0.6599326599326599

In [44]:
model_5 = make_pipeline(StandardScaler(),GaussianNB())

print(model_5.fit(X_train,y_train))

print(f'score Model:',model_5.score(X_test,y_test))

y_pred = model_5.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy= accuracy_score(y_test, y_pred)
print("Recall: ",recall_score(y_test, y_pred, average='micro'))
print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gaussiannb', GaussianNB())])
score Model: 0.48484848484848486
[[2 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
Recall:  0.48484848484848486
Precision: 0.48484848484848486
F1 PuanÄ±: 0.48484848484848486

In [51]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,roc_auc_score
values= [LogisticRegression(), SVC(), KNeighborsClassifier(), DecisionTreeClassifier(), GaussianNB()]

keys= ['LogisticRegression',
      'SVC', 
       'KNeighborsClassifier', 
       'DecisionTreeClassifier', 
       'GaussianNB']

models= dict(zip(keys,values))
accuracy_scores=[]
train_times=[]

for key,value in models.items():
  t = time()
  value.fit(X_train,y_train)
  duration = (time() - t) / 60
  y_pred= value.predict(X_test)
  accuracy= accuracy_score(y_test, y_pred)
  accuracy_scores.append(accuracy)
  train_times.append(duration)   
  print(key)
  print("Accuracy:",round(accuracy * 100, 2))
  #cm = confusion_matrix(y_test, y_pred)
  #print(cm)
  #print(classification_report(y_test, y_pred))
  print("Recall: ",recall_score(y_test, y_pred, average='micro'))
  print("Precision: "+str(precision_score(y_test,y_pred, average='micro')))
  print("F1 PuanÄ±: "+str(precision_score(y_test,y_pred, average='micro')))

LogisticRegression
Accuracy: 59.26
Recall:  0.5925925925925926
Precision: 0.5925925925925926
F1 PuanÄ±: 0.5925925925925926
SVC
Accuracy: 91.58
Recall:  0.9158249158249159
Precision: 0.9158249158249159
F1 PuanÄ±: 0.9158249158249159
KNeighborsClassifier
Accuracy: 87.21
Recall:  0.8720538720538721
Precision: 0.8720538720538721
F1 PuanÄ±: 0.8720538720538721
DecisionTreeClassifier
Accuracy: 65.99
Recall:  0.6599326599326599
Precision: 0.6599326599326599
F1 PuanÄ±: 0.6599326599326599
GaussianNB
Accuracy: 48.82
Recall:  0.4882154882154882
Precision: 0.4882154882154882
F1 PuanÄ±: 0.4882154882154882

In [25]:
test_pred = model_5.predict(df_test)
test_pred

array([50, 50,  1, 19, 14, 50, 50, 28, 16, 19, 43, 16, 75, 10, 52, 41, 69,
       19, 19, 71, 61, 69, 44, 77,  1, 87, 69, 15, 35, 70, 53, 16, 47, 50,
        4, 73, 93, 93, 69, 93, 19, 19, 19,  9, 71, 70, 38, 70, 19, 69, 86,
       19, 69, 94, 93, 86, 62, 69, 87,  0, 88, 26, 87, 59, 12, 11, 48, 78,
       13,  4, 85, 57, 79, 19, 31, 12, 19, 41, 47, 10, 61, 73, 85, 24, 19,
        2, 23, 56, 87, 73, 41, 69, 70, 83, 70, 56, 26, 17, 19, 48, 54, 93,
       50, 12, 69, 69, 12, 96, 64, 78, 93, 93, 36, 30, 16, 73, 60, 87,  6,
       44, 34, 69, 91, 14, 75, 27, 50, 92, 39, 23, 46,  2, 41, 68, 24, 93,
       28, 28, 69, 81, 42, 50, 50, 83, 60, 69, 14, 64, 42, 96, 14, 20, 59,
       35, 86,  1, 26, 38, 96, 83, 11, 60, 93, 79, 73, 79, 93, 47, 65, 77,
       26, 21, 79, 87, 11, 10, 73, 94, 27, 73, 19, 45, 73, 85, 47, 20, 87,
       94, 40, 49, 93, 70, 36, 93, 69, 95, 69, 91, 29, 64, 80,  6, 78, 45,
       12,  9, 78, 85, 77, 89, 92, 78,  2, 59, 41, 93, 70, 32, 79, 78, 91,
       69, 44, 34,  5, 79, 49, 58, 94, 67, 92, 88, 90, 11, 20, 39, 49, 12,
       76, 27, 70, 71, 11, 70, 33, 47, 98, 82, 34, 69, 36, 96, 48, 20, 62,
       64, 56, 50, 93, 73,  9, 19, 26, 19, 30, 71, 11, 36, 79, 47, 12, 78,
       73, 11, 27, 65, 36, 38,  0, 65, 50, 73, 47, 10, 80, 44, 73, 69, 54,
       54, 11, 51, 33, 93, 41, 11, 77,  1, 73,  2, 43, 83, 42, 86,  2, 73,
       96, 83, 73,  9, 63, 50, 16, 38, 87, 95, 50, 35, 41, 60, 59, 58, 87,
       93, 77, 38, 93, 50, 93, 93, 19, 46, 19, 93,  0, 33, 69, 70, 73, 48,
       42, 19, 69, 91, 73, 81, 12, 85, 47,  6, 79,  2, 73, 35, 43,  6, 80,
       78, 82, 56, 61, 70, 43, 33, 50, 47, 71, 58, 59, 69, 66, 86, 98, 50,
       90, 64, 78, 11, 11, 56, 85, 49, 48, 85, 16, 15, 54, 49, 89, 44, 17,
       35, 93, 54, 54, 96, 44, 19, 69, 26,  9, 36, 69, 61, 50, 82, 69, 79,
       22, 86, 72, 11, 19, 78, 87, 26, 12,  2, 74, 69, 66, 43, 26, 73, 80,
        4, 26,  3, 73, 87, 36, 93, 39, 69, 73, 76, 78,  7, 36, 70,  8, 95,
       85, 62, 10, 87, 48,  2, 52, 86, 48, 52,  3, 49, 47, 87, 52, 41, 26,
       88, 71, 45, 69, 27, 87, 75, 74, 11, 64, 65, 78, 63, 83, 21, 54, 88,
       83, 11, 26, 12, 16, 36, 85, 12, 77, 57, 50, 82, 70, 19, 69, 19, 36,
       77, 73, 66, 83, 35, 48, 48, 54, 91, 20, 19, 15, 10, 24, 71, 73, 12,
       54, 85, 16, 19, 45, 74,  6, 47, 42, 34, 80, 12, 85, 69, 85, 47, 47,
       27, 58, 68, 41, 97, 63, 91, 76, 96, 87, 36, 14,  0, 19, 41, 14, 12,
        0, 86, 46, 19,  4, 47, 69, 19, 58, 19, 93, 12, 78, 14, 72, 93, 87,
       78, 69, 50, 26, 92, 16, 81, 37, 14, 93, 19, 56, 46, 25, 50, 17, 37,
       93,  0, 20, 41, 10, 91, 69, 81, 53, 18, 27, 11, 12, 65, 19, 36])

In [26]:
sample_df=pd.read_csv('/Users/isa/Desktop/LeafClassification/sample_submission.csv',index_col=False)
print(sample_df)

       id  Acer_Capillipes  Acer_Circinatum  Acer_Mono  Acer_Opalus  \
0       4         0.010101         0.010101   0.010101     0.010101
1       7         0.010101         0.010101   0.010101     0.010101
2       9         0.010101         0.010101   0.010101     0.010101
3      12         0.010101         0.010101   0.010101     0.010101
4      13         0.010101         0.010101   0.010101     0.010101
..    ...              ...              ...        ...          ...
589  1576         0.010101         0.010101   0.010101     0.010101
590  1577         0.010101         0.010101   0.010101     0.010101
591  1579         0.010101         0.010101   0.010101     0.010101
592  1580         0.010101         0.010101   0.010101     0.010101
593  1583         0.010101         0.010101   0.010101     0.010101

     Acer_Palmatum  Acer_Pictum  Acer_Platanoids  Acer_Rubrum  Acer_Rufinerve  \
0         0.010101     0.010101         0.010101     0.010101        0.010101
1         0.010101     0.010101         0.010101     0.010101        0.010101
2         0.010101     0.010101         0.010101     0.010101        0.010101
3         0.010101     0.010101         0.010101     0.010101        0.010101
4         0.010101     0.010101         0.010101     0.010101        0.010101
..             ...          ...              ...          ...             ...
589       0.010101     0.010101         0.010101     0.010101        0.010101
590       0.010101     0.010101         0.010101     0.010101        0.010101
591       0.010101     0.010101         0.010101     0.010101        0.010101
592       0.010101     0.010101         0.010101     0.010101        0.010101
593       0.010101     0.010101         0.010101     0.010101        0.010101

     ...  Salix_Fragilis  Salix_Intergra  Sorbus_Aria  Tilia_Oliveri  \
0    ...        0.010101        0.010101     0.010101       0.010101
1    ...        0.010101        0.010101     0.010101       0.010101
2    ...        0.010101        0.010101     0.010101       0.010101
3    ...        0.010101        0.010101     0.010101       0.010101
4    ...        0.010101        0.010101     0.010101       0.010101
..   ...             ...             ...          ...            ...
589  ...        0.010101        0.010101     0.010101       0.010101
590  ...        0.010101        0.010101     0.010101       0.010101
591  ...        0.010101        0.010101     0.010101       0.010101
592  ...        0.010101        0.010101     0.010101       0.010101
593  ...        0.010101        0.010101     0.010101       0.010101

     Tilia_Platyphyllos  Tilia_Tomentosa  Ulmus_Bergmanniana  Viburnum_Tinus  \
0              0.010101         0.010101            0.010101        0.010101
1              0.010101         0.010101            0.010101        0.010101
2              0.010101         0.010101            0.010101        0.010101
3              0.010101         0.010101            0.010101        0.010101
4              0.010101         0.010101            0.010101        0.010101
..                  ...              ...                 ...             ...
589            0.010101         0.010101            0.010101        0.010101
590            0.010101         0.010101            0.010101        0.010101
591            0.010101         0.010101            0.010101        0.010101
592            0.010101         0.010101            0.010101        0.010101
593            0.010101         0.010101            0.010101        0.010101

     Viburnum_x_Rhytidophylloides  Zelkova_Serrata
0                        0.010101         0.010101
1                        0.010101         0.010101
2                        0.010101         0.010101
3                        0.010101         0.010101
4                        0.010101         0.010101
..                            ...              ...
589                      0.010101         0.010101
590                      0.010101         0.010101
591                      0.010101         0.010101
592                      0.010101         0.010101
593                      0.010101         0.010101

[594 rows x 100 columns]

In [27]:
output = pd.DataFrame({'Id': test_id,
                       
                       'Labels': test_pred})
output.to_csv('submission.csv', index=False)
output.head()

   Id  Labels
0   4      50
1   7      50
2   9       1
3  12      19
4  13      14

In [28]:
final=pd.concat([output,sample_df],axis=1)
final.head()

,Id,Labels,id,Acer_Capillipes,Acer_Circinatum,Acer_Mono,Acer_Opalus,Acer_Palmatum,Acer_Pictum,Acer_Platanoids,...,Salix_Fragilis,Salix_Intergra,Sorbus_Aria,Tilia_Oliveri,Tilia_Platyphyllos,Tilia_Tomentosa,Ulmus_Bergmanniana,Viburnum_Tinus,Viburnum_x_Rhytidophylloides,Zelkova_Serrata
0,4,50,4,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
1,7,50,7,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
2,9,1,9,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
3,12,19,12,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101
4,13,14,13,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,...,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101,0.010101